// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sazqeczlnprcbeozxjyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhenFlY3psbnByY2Jlb3p4anlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDI1MzAsImV4cCI6MjA2Nzk3ODUzMH0.o-rMcI-J5H1Ovwz8N3zNnx_-Im5X3r7ETyql_bAHZHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});